/**
 * OWNER: M4 — Platform / Risk Lead
 * Message formatting utilities for Telegram alerts and reports.
 */

import type {
  TelegramAlertPayload,
  TelegramEodDigestPayload,
  PortfolioState,
} from "@committee/contracts";

export class TelegramFormatter {
  /**
   * Formats a real-time trade decision alert.
   */
  static formatTradeAlert(payload: TelegramAlertPayload): string {
    const actionEmoji =
      payload.action === "BUY" ? "🟢" : payload.action === "SELL" ? "🔴" : "⚪";
    const confidencePct = Math.round(payload.confidence * 100);
    const riskStatus = payload.riskApproved
      ? "✅ *APPROVED*"
      : "🛡️ *BLOCKED BY RISK GATE*";

    const lines: string[] = [
      `${actionEmoji} *QUANT COMMITTEE SIGNAL: ${payload.action} ${payload.symbol}*`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `• *Confidence:* ${confidencePct}%`,
    ];

    if (payload.price !== undefined) {
      lines.push(`• *Decision Price:* \$${payload.price.toFixed(2)}`);
    }

    if (payload.allocatedQty !== undefined && payload.allocatedQty > 0) {
      lines.push(`• *Allocated Sizing:* ${payload.allocatedQty} shares`);
    }

    lines.push(`• *Risk Check:* ${riskStatus}`);
    if (!payload.riskApproved && payload.riskReason) {
      lines.push(`• *Risk Rule Triggered:* _${payload.riskReason}_`);
    }

    lines.push(
      ``,
      `📖 *Consensus Rationale:*`,
      `${payload.rationale}`,
    );

    if (payload.debateDissent) {
      lines.push(
        ``,
        `⚖️ *Preserved Dissent:*`,
        `_${payload.debateDissent}_`,
      );
    }

    lines.push(
      ``,
      `⏱️ _Decision Time: ${new Date(payload.decisionTs).toUTCString()}_`,
    );

    return lines.join("\n");
  }

  /**
   * Formats an End-of-Day digest.
   */
  static formatEodDigest(payload: TelegramEodDigestPayload): string {
    const sign = payload.dayChange >= 0 ? "+" : "";
    const changeEmoji = payload.dayChange >= 0 ? "📈" : "📉";

    const lines: string[] = [
      `${changeEmoji} *DAILY TRADING DIGEST — ${new Date(payload.asOf).toISOString().slice(0, 10)}*`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `• *Total Portfolio Equity:* \$${payload.portfolioEquity.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `• *Unallocated Cash:* \$${payload.cash.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `• *Day Change:* ${sign}\$${payload.dayChange.toFixed(2)} (${sign}${payload.dayChangePercent.toFixed(2)}%)`,
      `• *Executed Trades Today:* ${payload.executedTradesCount}`,
    ];

    if (payload.topPositions.length > 0) {
      lines.push(``, `📊 *Active Portfolio Positions:*`);
      for (const pos of payload.topPositions) {
        const plStr =
          pos.unrealizedPl !== undefined
            ? ` | P&L: ${pos.unrealizedPl >= 0 ? "+" : ""}\$${pos.unrealizedPl.toFixed(2)}`
            : "";
        lines.push(
          `  - *${pos.symbol}*: ${pos.qty} shares (\$${pos.marketValue.toFixed(2)}${plStr})`,
        );
      }
    } else {
      lines.push(``, `📊 *Active Positions:* None (100% Cash)`);
    }

    lines.push(
      ``,
      `_Automated recap generated by QuantAgent Committee._`,
    );

    return lines.join("\n");
  }

  /**
   * Formats current portfolio snapshot.
   */
  static formatPortfolio(state: PortfolioState): string {
    const lines: string[] = [
      `💼 *PORTFOLIO STATUS*`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `• *Total Equity:* \$${state.equity.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `• *Available Cash:* \$${state.cash.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `• *As Of:* _${new Date(state.asOf).toUTCString()}_`,
    ];

    if (state.positions.length > 0) {
      lines.push(``, `*Open Positions:*`);
      for (const p of state.positions) {
        const plStr =
          p.unrealizedPl !== undefined
            ? ` | Unrealized P&L: ${p.unrealizedPl >= 0 ? "+" : ""}\$${p.unrealizedPl.toFixed(2)}`
            : "";
        lines.push(`• *${p.symbol}*: ${p.qty} shares (\$${p.marketValue.toFixed(2)}${plStr})`);
      }
    } else {
      lines.push(``, `*Open Positions:* (No active positions)`);
    }

    return lines.join("\n");
  }

  /**
   * Formats watchlist items.
   */
  static formatWatchlist(items: { symbol: string }[]): string {
    if (items.length === 0) {
      return "📋 *Watchlist is currently empty.*\nUse the web dashboard to add tickers.";
    }

    const symbols = items.map((i) => `• \`${i.symbol}\``).join("\n");
    return `📋 *ACTIVE WATCHLIST TICKERS:*\n━━━━━━━━━━━━━━━━━━━━━━\n${symbols}`;
  }

  /**
   * Formats help message.
   */
  static formatHelp(): string {
    return [
      `🤖 *QuantAgent Committee Telegram Bot*`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `Available commands:`,
      `• \`/portfolio\` — View current paper equity, cash, and open positions.`,
      `• \`/latest\` — View the most recent multi-agent committee decision.`,
      `• \`/watchlist\` — List tracked market symbols.`,
      `• \`/eod\` — Request on-demand daily summary recap.`,
      `• \`/help\` — Display this command reference.`,
      ``,
      `_Point-in-time disciplined multi-agent paper trading system._`,
    ].join("\n");
  }
}
